### ISSUE TITLE
openscad-format produces empty output files

### ISSUE THREAD

**Issue by alexbirkett** [Maxattax97/openscad-format#8] opened 2020-05-23 07:48 UTC
`openscad-format` produces empty output files. No error message is displayed. I suspect it might be something to do with a peer dependency `eslint-config-airbnb-base` 

Here are the steps I performed:

```Alexs-MacBook-Pro-2124:wing alex$ node-v
-bash: node-v: command not found
Alexs-MacBook-Pro-2124:wing alex$ node -v
v12.16.3
Alexs-MacBook-Pro-2124:wing alex$ npm -v
6.14.4
Alexs-MacBook-Pro-2124:wing alex$ npm install -g openscad-format
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
/usr/local/bin/openscad-format -> /usr/local/lib/node_modules/openscad-format/index.js
npm WARN openscad-format@1.0.0 requires a peer of eslint-config-airbnb-base@^13.1.0 but none is installed. You must install peer dependencies yourself.

+ openscad-format@1.0.0
updated 1 package in 5.246s
Alexs-MacBook-Pro-2124:wing alex$ openscad-format < interpolate.scad > interpolate2.scad 
Alexs-MacBook-Pro-2124:wing alex$ more interpolate2.scad
```

**Comment by Maxattax97** [comment] 2020-05-23 17:41
Could you provide your source file, `interpolate.scad`?

**Comment by Maxattax97** [comment] 2020-07-21 01:18
Closing as I cannot reproduce. Can re-open if we see this issue again.

**Closed by Maxattax97** 2020-07-21 01:18 UTC

**Comment by blackmad** [comment] 2021-05-12 14:10
this is consistently happening to me


~ ─────────────────────────────────────────────────── took 9s at 10:05:47 AM ─╮
❯ node -v                                                                    ─╯
v14.16.1

~ ─────────────────────────────────────────────────────────── at 10:08:48 AM ─╮
❯ npm -v                                                                     ─╯
7.11.2

~ ─────────────────────────────────────────────────────────── at 10:08:49 AM ─╮
❯ openscad-format --version                                                  ─╯
1.0.0

~ ─────────────────────────────────────────────────────────── at 10:08:54 AM ─╮
❯ uname -a                                                                   ─╯
Darwin Davids-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64


~/Dropbox/My Mac (Davids-MacBook-Pro.local)/Desktop ─────────────────────────────────────────────────────────── at 10:10:09 AM ─╮
❯ openscad-format < ikea_skadis.scad                                                                                           ─╯


[ikea_skadis 2.scad.txt](https://github.com/Maxattax97/openscad-format/files/6466725/ikea_skadis.2.scad.txt)
